### ISSUE TITLE
Which programming language you used

### ISSUE THREAD

**Issue by PSGitHubUser1** [Lixkote/Startify#1]
Which of the following you have used for WinUI 3? (MCQ)

- C# and .NET
- C# and Xaml 

I want to know please tell.

**Comment by arin2115** [comment]
You're right @Maks1116, he used C and assembly for Startify.

**Comment by Lixkote** [comment]
@PSGitHubUser1 
Jokes aside, i've used WPF c# for the backend and UWP c# for the frontend. 
The two types were combined using XamlIslands.

**Comment by PSGitHubUser1** [comment]
> @PSGitHubUser1 
> Jokes aside, i've used WPF c# for the backend and UWP c# for the frontend. 
> The two types were combined using XamlIslands.

How this is possible? I just started learn C# with Xaml.. In VS but I didn't that we can use like C# and Xaml at behind and like C# and .NET at front..

 I just read your comment, I have no idea how that's possible like C# & Xaml and C# &. NET to use in one project like how bro??? 11?

If thats possible then why there is option at beginning to choose one?

I j- jus- just don't understand, please tell me I am a beginner in VS and C# both..
