### ISSUE TITLE
pinyin character cannot follow alphabet character

### ISSUE THREAD

**Issue by ZHang233-ai** [Lixkote/Startify#10]
![image](https://github.com/user-attachments/assets/0cab8d89-a9fc-4677-9664-ea00c1311bbb)
Here's some information about it

https://www.cnblogs.com/glacierh/archive/2008/08/25/1276113.html
https://edi.wang/post/2016/9/22/windows-10-uwp-fark-pinyin-group

Hope could fix it asap : )

**Comment by Lixkote** [comment]
@Sanlorng already fixed it, thanks very much for pointing out tho. Also much thanks for the fix
