### ISSUE TITLE
Startify remains hooked after removal

### ISSUE THREAD

**Issue by thatpanda0** [Lixkote/Startify#22]
Windows 10 19045.2965
Startify 0.2

Upon uninstallation, Startify remains the start menu and refuses to unattach, even after:
- Restarting Explorer
- Restarting Windows

![image](https://github.com/user-attachments/assets/19aa4633-facb-454b-9b62-284f9e6579fa)
![image](https://github.com/user-attachments/assets/c22667a4-53e6-4e64-bac2-4d220caf38d8)

**Comment by Lixkote** [comment]
> Windows 10 19045.2965 Startify 0.2
> 
> Upon uninstallation, Startify remains the start menu and refuses to unattach, even after:
> 
> * Restarting Explorer
> * Restarting Windows
> 
> ![image](https://private-user-images.githubusercontent.com/165739041/384716332-19aa4633-facb-454b-9b62-284f9e6579fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODI3ODIsIm5iZiI6MTczMTc4MjQ4MiwicGF0aCI6Ii8xNjU3MzkwNDEvMzg0NzE2MzMyLTE5YWE0NjMzLWZhY2ItNDU0Yi05YjYyLTI4NGY5ZTY1NzlmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxODQxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2M3ODlkZTc0NmRjOTQyMDQ2NzkwOTcwYWZiOTdmNDM2ZDYwYzViODMwZDhiMWQzMzQyMmQ2MmQ2M2RkNjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BHTK2eo8NHPK_K-8uCRieQBUO0LGIixs-FxZWC3dxuE) ![image](https://private-user-images.githubusercontent.com/165739041/384716352-c22667a4-53e6-4e64-bac2-4d220caf38d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODI3ODIsIm5iZiI6MTczMTc4MjQ4MiwicGF0aCI6Ii8xNjU3MzkwNDEvMzg0NzE2MzUyLWMyMjY2N2E0LTUzZTYtNGU2NC1iYWMyLTRkMjIwY2FmMzhkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxODQxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjY3OWQ1MzhkZDE1MTk5NWU5NDlmMjZkOWIxYmIyNjBhMzQwYTIxMzEyZDY4M2Y4ZGRkYTYyMGU1YzQzMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k6kHTRWJSf1OXPnURrV3fauf-WHChsQ6xTftaPd00kM)

Startify does not support Windows 10, and likely never will. Please do not report bugs from Windows 10.
