### ISSUE TITLE
If you drag an item from the start menu into any input field, your start menu won't open anymore.

### ISSUE THREAD

**Issue by 0x76616c** [Lixkote/Startify#24]
![DiscordCanary_dPi629f4Sw](https://github.com/user-attachments/assets/e0861de7-beeb-4353-9ffa-eed15a269fe1)

what the fuck.....
i reloaded the debug build and it still wont open

**Comment by Lixkote** [comment]
https://www.youtube.com/watch?v=YPN0qhSyWy8

**Comment by 0x76616c** [comment]
![explorer_iseAWqq461](https://github.com/user-attachments/assets/adb37eca-a124-4449-98ac-e8db50a82df8)
WHAT THE FUCK

**Comment by Lixkote** [comment]
> ![explorer_iseAWqq461](https://private-user-images.githubusercontent.com/118563924/399019993-adb37eca-a124-4449-98ac-e8db50a82df8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDA3NTUsIm5iZiI6MTczNTM0MDQ1NSwicGF0aCI6Ii8xMTg1NjM5MjQvMzk5MDE5OTkzLWFkYjM3ZWNhLWExMjQtNDQ0OS05OGFjLWU4ZGI1MGE4MmRmOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QyMzAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGRjOGY1ZDYwZWJkYzA4MzJlYTQ1NjFiYWQyNmExZmY5MzAwYzFiZmQ2NDIxMmU4ZWUyZDVjZGMzNTk5YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FLVG-wiyfqhPwhNTlUgP8ufYO-X1eb_xWhCUgqDuQXw) [ ![explorer_iseAWqq461](https://private-user-images.githubusercontent.com/118563924/399019993-adb37eca-a124-4449-98ac-e8db50a82df8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDA3NTUsIm5iZiI6MTczNTM0MDQ1NSwicGF0aCI6Ii8xMTg1NjM5MjQvMzk5MDE5OTkzLWFkYjM3ZWNhLWExMjQtNDQ0OS05OGFjLWU4ZGI1MGE4MmRmOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QyMzAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGRjOGY1ZDYwZWJkYzA4MzJlYTQ1NjFiYWQyNmExZmY5MzAwYzFiZmQ2NDIxMmU4ZWUyZDVjZGMzNTk5YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FLVG-wiyfqhPwhNTlUgP8ufYO-X1eb_xWhCUgqDuQXw) ](https://private-user-images.githubusercontent.com/118563924/399019993-adb37eca-a124-4449-98ac-e8db50a82df8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDA3NTUsIm5iZiI6MTczNTM0MDQ1NSwicGF0aCI6Ii8xMTg1NjM5MjQvMzk5MDE5OTkzLWFkYjM3ZWNhLWExMjQtNDQ0OS05OGFjLWU4ZGI1MGE4MmRmOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QyMzAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGRjOGY1ZDYwZWJkYzA4MzJlYTQ1NjFiYWQyNmExZmY5MzAwYzFiZmQ2NDIxMmU4ZWUyZDVjZGMzNTk5YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FLVG-wiyfqhPwhNTlUgP8ufYO-X1eb_xWhCUgqDuQXw) [ ](https://private-user-images.githubusercontent.com/118563924/399019993-adb37eca-a124-4449-98ac-e8db50a82df8.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDA3NTUsIm5iZiI6MTczNTM0MDQ1NSwicGF0aCI6Ii8xMTg1NjM5MjQvMzk5MDE5OTkzLWFkYjM3ZWNhLWExMjQtNDQ0OS05OGFjLWU4ZGI1MGE4MmRmOC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyN1QyMzAwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNGRjOGY1ZDYwZWJkYzA4MzJlYTQ1NjFiYWQyNmExZmY5MzAwYzFiZmQ2NDIxMmU4ZWUyZDVjZGMzNTk5YmIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FLVG-wiyfqhPwhNTlUgP8ufYO-X1eb_xWhCUgqDuQXw) WHAT THE FUCK

Actually its not a bug its a 🌠feature 🌠 called DualStartMenus™.

**Comment by 0x76616c** [comment]
NOW MY SEARCH IN NORMAL START MENU DOESNT WORK

**Comment by Lixkote** [comment]
> NOW MY SEARCH IN NORMAL START MENU DOESNT WORK

skill issue :)

**Comment by 0x76616c** [comment]
this repo deserves 10k stars

**Comment by Lixkote** [comment]
> this repo deserves 10k stars

i ahree

**Comment by Maks1116** [comment]
"It just works, it just works
Little lies, stunning shows
People buy, money flows, it just works
It just works, it just works"
