### ISSUE TITLE
Outdated framework

### ISSUE THREAD

**Issue by OrionFOTL** [Lixkote/Startify#4]
.NET Core 3.1 was released 5 years ago (12.2019), and went out of support in December 2022. It was since been superseded by .NET 5, 6, 7, and currently .NET 8. 

Using .NET Core 3.1 to develop this project, and requiring users to install an unsupported runtime seems strange. Is this very intentional, or is it a tech debt that is planned to be updated to a current framework?

**Comment by Izuku-Sevilla** [comment]
I'm not the developer of course. But I do have followed the work of this project. As far as I know this is a couple of technical reasons and to still ensure the use of the app on windows 10

but the main reason the Lixote said a while ago is becase he wanted to use XAML Island and as far as i remember was only supported on .NET 3.x
and as I Was checking microsoft resources for fact checking

_"Using XAML Islands in WPF and Windows Forms apps that target the .NET Framework. XAML Islands are supported only in apps that target.NET Core 3.x."_

https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands

**Comment by Lixkote** [comment]
> .NET Core 3.1 was released 5 years ago (12.2019), and went out of support in December 2022. It was since been superseded by .NET 5, 6, 7, and currently .NET 8.
> 
> Using .NET Core 3.1 to develop this project, and requiring users to install an unsupported runtime seems strange. Is this very intentional, or is it a tech debt that is planned to be updated to a current framework?

This is absolutely intentional, as from my testing, xaml islands (which are only supported on .net 3.1) allow for much stabler, and less resource intensive app than new solutions from microsoft. I may consider rewriting this application later on in something newer, but i kinda do not see the point in doing so for now.
