### ISSUE TITLE
Program not launching at all

### ISSUE THREAD

**Issue by mad4me** [Lixkote/Startify#6]
The programm kinda launches for a second, but its disables in 1 second, and it only sends the notfication, no signs of life for this programm. Can't give much info bc idk how to give more feedback, as it doesnt give any error codes, its just lags like hell, gives 2 notifications that it works, and there is no new start menu.

**Comment by Lixkote** [comment]
Paste this file into %HOMEPATH%\Startify\ 
https://github.com/Lixkote/Startify/releases/download/0.1/Settings.cfg

**Comment by mad4me** [comment]
It worked, but the program is buggy overall, I tough the Issue might be with startallback so i disbabled, and it was less buggy, but it still takes time to close, or to open. Sometimes when i press the start button on the keyboard, it doesn't open, but the start button changes like its open and sometimes the start menu opens 2 times.

**Comment by Lixkote** [comment]
> It worked, but the program is buggy overall, I tough the Issue might be with startallback so i disbabled, and it was less buggy, but it still takes time to close, or to open. Sometimes when i press the start button on the keyboard, it doesn't open, but the start button changes like its open and sometimes the start menu opens 2 times.

Please provide more information about your windows installation (build number, version, sku, screen resolution, and screen scale)

**Comment by mad4me** [comment]
> Please provide more information about your windows installation (build number, version, sku, screen resolution, and screen scale)

Windows version: Windows 11 23H2
Build number: 22631.3880
Screen resolution: FHD (1920x1080)
Screen scale: 100%

(no idea what sku is and i couldnt find information about it)

**Comment by Lixkote** [comment]
> > Please provide more information about your windows installation (build number, version, sku, screen resolution, and screen scale)
> 
> Windows version: Windows 11 23H2 Build number: 22631.3880 Screen resolution: FHD (1920x1080) Screen scale: 100%
> 
> (no idea what sku is and i couldnt find information about it)

Thanks i will look into it, another question is do you have the language "English (USA)" set as default in Windows Settings?

**Comment by mad4me** [comment]
> Thanks i will look into it, another question is do you have the language "English (USA)" set as default in Windows Settings?

yes
