### ISSUE TITLE
[Feature request] The start button is placed on the left, but the other buttons are placed in the middle.

### ISSUE THREAD

**Issue by Shomnipotence** [Lixkote/Startify#9]
![image](https://github.com/user-attachments/assets/bc5c7ce5-dbe6-410f-ab25-a681856759a0)
We may not be able to do this easily, so is it possible to simply cover the start button?

**Comment by Lixkote** [comment]
This is related to the start button hook mechanism, this will be fixed at the same time i came up with a new hooking mechanism.

**Comment by Shomnipotence** [comment]
> This is related to the start button hook mechanism, this will be fixed at the same time i came up with a new hooking mechanism.

This is not a bug, it's a feature request. I want a single start menu button on the left. Start11 can do it (of course it does it by writing its own taskbar, not modifying the existing taskbar). It may be difficult to do this while keeping the existing taskbar functionality, but I still hope you can try it.

@Lixkote

**Comment by Lixkote** [comment]
> > This is related to the start button hook mechanism, this will be fixed at the same time i came up with a new hooking mechanism.
> 
> This is not a bug, it's a feature request. I want a single start menu button on the left. Start11 can do it (of course it does it by writing its own taskbar, not modifying the existing taskbar). It may be difficult to do this while keeping the existing taskbar functionality, but I still hope you can try it.
> 
> @Lixkote

Well, currently startify it not focusing on taskbar enachancements. Maybe in the future...
